# Generated by Django 4.1.4 on 2022-12-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_mymodel_alter_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Label',
        ),
    ]
