# Generated by Django 4.1.4 on 2022-12-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_rename_mymodel_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='label.image'),
            preserve_default=False,
        ),
    ]
