# Generated by Django 4.1.4 on 2023-01-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0006_remove_label_image_delete_image_delete_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ImageID', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Starttime', models.CharField(max_length=500)),
                ('Endtime', models.CharField(max_length=500)),
                ('Duration', models.CharField(max_length=500)),
                ('Errors', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('ImageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='label.image')),
                ('LabelMaterial', models.CharField(choices=[], max_length=500)),
                ('LabelTerrain', models.CharField(choices=[('Gras / Wiese', 'Gras / Wiese'), ('Asphalt', 'Asphalt'), ('Strand / Sand', 'Strand / Sand'), ('Öffentliches Verkehrsmittel', 'Öffentliches Verkehrsmittel')], max_length=500)),
                ('LabelItemType', models.CharField(choices=[('Löffel', 'Löffel'), ('PET-Flasche', 'PET-Flasche'), ('Verpackung', 'Verpackung'), ('Beutel', 'Beutel'), ('Deckel', 'Deckel'), ('Strohhalm', 'Strohhalm')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SessionLabel',
            fields=[
                ('ImageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='label.image')),
                ('LabelMaterial_labeled', models.CharField(choices=[], max_length=500)),
                ('LabelTerrain_labeled', models.CharField(choices=[('Gras / Wiese', 'Gras / Wiese'), ('Asphalt', 'Asphalt'), ('Strand / Sand', 'Strand / Sand'), ('Öffentliches Verkehrsmittel', 'Öffentliches Verkehrsmittel')], max_length=500)),
                ('LabelItemType_labeled', models.CharField(choices=[('Löffel', 'Löffel'), ('PET-Flasche', 'PET-Flasche'), ('Verpackung', 'Verpackung'), ('Beutel', 'Beutel'), ('Deckel', 'Deckel'), ('Strohhalm', 'Strohhalm')], max_length=500)),
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.session')),
            ],
        ),
    ]
