# Generated by Django 4.1.4 on 2023-01-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ImageID',
            field=models.BigIntegerField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
