# Generated by Django 4.1.4 on 2023-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_alter_image_imageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ImageID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
