# Generated by Django 4.1.4 on 2023-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0010_coinlabel_sessioncoinlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncoinlabel',
            name='LabelCoinValue_labeled',
        ),
        migrations.RemoveField(
            model_name='sessioncoinlabel',
            name='LabelCoinValue_labeled_currency',
        ),
    ]
