# Generated by Django 4.1.4 on 2023-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0011_remove_sessioncoinlabel_labelcoinvalue_labeled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinlabel',
            name='LabelCoinValue_currency',
        ),
        migrations.AddField(
            model_name='sessioncoinlabel',
            name='LabelCoinValue_labeled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinlabel',
            name='LabelCoinValue',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
