# Generated by Django 4.1.4 on 2023-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0012_remove_coinlabel_labelcoinvalue_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncoinlabel',
            name='LabelCoinCount_labeled',
            field=models.BigIntegerField(verbose_name='Anzahl der Münzen'),
        ),
        migrations.AlterField(
            model_name='sessioncoinlabel',
            name='LabelCoinValue_labeled',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Wert der Münzen (in EUR.)'),
        ),
    ]
