# Generated by Django 4.1.4 on 2023-01-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0013_alter_sessioncoinlabel_labelcoincount_labeled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncoinlabel',
            name='ImageID',
        ),
        migrations.RemoveField(
            model_name='sessioncoinlabel',
            name='SessionID',
        ),
        migrations.DeleteModel(
            name='CoinLabel',
        ),
        migrations.DeleteModel(
            name='SessionCoinLabel',
        ),
    ]
