# Generated by Django 4.1.4 on 2023-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0014_remove_sessioncoinlabel_imageid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='LabelItemType',
            field=models.CharField(choices=[('Löffel', 'Löffel'), ('PET-Flasche', 'PET-Flasche'), ('Verpackung', 'Verpackung'), ('Beutel', 'Beutel'), ('Deckel', 'Deckel'), ('Strohhalm', 'Strohhalm')], max_length=500, verbose_name='Gegenstand'),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='LabelTerrain',
            field=models.CharField(choices=[('Gras / Wiese', 'Gras / Wiese'), ('Asphalt', 'Asphalt'), ('Strand / Sand', 'Strand / Sand'), ('Öffentliches Verkehrsmittel', 'Öffentliches Verkehrsmittel')], max_length=500, verbose_name='Terrain'),
        ),
    ]
