# Generated by Django 4.1.5 on 2023-01-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0015_alter_imagelabel_labelitemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='LabelItemType',
            field=models.CharField(choices=[('Plastiklöffel', 'Plastiklöffel'), ('PET-Flasche', 'PET-Flasche'), ('Glasflasche', 'Glasflasche'), ('Kein Müllgegestand', 'Kein Müllgegestan'), ('Plastikbeutel', 'Plastikbeutel'), ('Flaschendeckel', 'Flaschendeckel'), ('Strohhalm', 'Strohhalm'), ('Verpackung', 'Verpackung'), ('Tetrapack', 'Tetrapack'), ('Getränkedose', 'Getränkedose')], max_length=500, verbose_name='Gegenstand'),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='LabelTerrain',
            field=models.CharField(choices=[('Wiese', 'Wiese'), ('Asphalt', 'Asphalt'), ('Sand', 'Sand'), ('Öffentliches Verkehrsmittel', 'Öffentliches Verkehrsmittel')], max_length=500, verbose_name='Terrain'),
        ),
        migrations.AlterField(
            model_name='sessionlabel',
            name='LabelItemType_labeled',
            field=models.CharField(choices=[('Plastiklöffel', 'Plastiklöffel'), ('PET-Flasche', 'PET-Flasche'), ('Glasflasche', 'Glasflasche'), ('Kein Müllgegestand', 'Kein Müllgegestan'), ('Plastikbeutel', 'Plastikbeutel'), ('Flaschendeckel', 'Flaschendeckel'), ('Strohhalm', 'Strohhalm'), ('Verpackung', 'Verpackung'), ('Tetrapack', 'Tetrapack'), ('Getränkedose', 'Getränkedose')], max_length=500),
        ),
        migrations.AlterField(
            model_name='sessionlabel',
            name='LabelTerrain_labeled',
            field=models.CharField(choices=[('Wiese', 'Wiese'), ('Asphalt', 'Asphalt'), ('Sand', 'Sand'), ('Öffentliches Verkehrsmittel', 'Öffentliches Verkehrsmittel')], max_length=500),
        ),
    ]
