# Generated by Django 4.1.5 on 2023-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0016_alter_imagelabel_labelitemtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='LabelItemType',
            field=models.CharField(choices=[('Plastiklöffel', 'Plastiklöffel'), ('PET-Flasche', 'PET-Flasche'), ('Glasflasche', 'Glasflasche'), ('Kein Müllgegestand', 'Kein Müllgegestand'), ('Plastikbeutel', 'Plastikbeutel'), ('Flaschendeckel', 'Flaschendeckel'), ('Strohhalm', 'Strohhalm'), ('Verpackung', 'Verpackung'), ('Tetrapack', 'Tetrapack'), ('Getränkedose', 'Getränkedose')], max_length=500, verbose_name='Gegenstand'),
        ),
        migrations.AlterField(
            model_name='sessionlabel',
            name='LabelItemType_labeled',
            field=models.CharField(choices=[('Plastiklöffel', 'Plastiklöffel'), ('PET-Flasche', 'PET-Flasche'), ('Glasflasche', 'Glasflasche'), ('Kein Müllgegestand', 'Kein Müllgegestand'), ('Plastikbeutel', 'Plastikbeutel'), ('Flaschendeckel', 'Flaschendeckel'), ('Strohhalm', 'Strohhalm'), ('Verpackung', 'Verpackung'), ('Tetrapack', 'Tetrapack'), ('Getränkedose', 'Getränkedose')], max_length=500),
        ),
    ]
